# Configuration file to install the recipe dependencies inside the Podman container

FROM docker.io/rockylinux/rockylinux:9

RUN dnf -y install 'dnf-command(config-manager)' epel-release \
    && dnf config-manager --set-enabled crb \
    && dnf -y update

RUN dnf -y install --allowerasing \
        appstream \
        appstream-compose \
        autoconf \
        autoconf-archive \
        automake \
        bison \
        cmake \
        curl \
        dos2unix \
        doxygen \
        expect \
        file \
        flex \
        fuse3 \
        fuse3-devel \
        gcc \
        gcc-c++ \
        genisoimage \
        gettext-devel \
        git \
        git-lfs \
        glib2-devel \
        gobject-introspection \
        gtk-doc \
        gtk-update-icon-cache \
        help2man \
        intltool \
        ipxe-bootimgs \
        dbus-glib \
        librsvg2 \
        lzip \
        m4 \
        make \
        meson \
        nano \
        nasm \
        ninja-build \
        openssh-clients \
        patch \
        patchelf \
        perl \
        perl-HTML-Parser \
        pkgconf-pkg-config \
        po4a \
        protobuf-compiler \
        python3 \
        python3-devel \
        python3-libxml2 \
        python3-mako \
        python3-pip \
        python3-pyyaml \
        rsync \
        ruby \
        scons \
        SDL-devel \
        SDL2_ttf-devel \
        texinfo \
        unifdef \
        unzip \
        util-linux \
        vim-common \
        wget \
        xdg-utils \
        xorg-x11-server-devel \
        xorg-x11-util-macros \
        zip \
        zstd \
    && if [ "$(uname -m)" = "x86_64" ]; then \
        dnf -y install \
            glibc-devel.i686 \
            syslinux; \
       fi \
    && dnf clean all

# TODO: Rust installation. But CI defaults to /github/home
