[packages]
acid = "TODO"
autoconf = "TODO"
automake = "TODO"
base-initfs = "TODO"
base = "TODO"
bash = "TODO"
bootloader = "TODO"
ca-certificates = "TODO"
contain = "TODO"
coreutils = "TODO"
cosmic-edit = "TODO"
cosmic-files = "TODO"
cosmic-icons = "TODO"
cosmic-term = "TODO"
curl = "TODO"
dejavu = "TODO"
diffutils = "TODO"
drivers = "TODO"
extrautils = "TODO"
findutils = "TODO"
gettext = "TODO"
git = "TODO"
gnu-grep = "TODO"
gnu-make = "TODO"
hicolor-icon-theme = "TODO"
installer-gui = "TODO"
installer = "TODO"
ion = "TODO"
kernel = "TODO"
kibi = "TODO"
libffi = "TODO"
libgcc = "TODO"
libgmp = "TODO"
libiconv = "TODO"
libjpeg = "TODO"
libogg = "TODO"
liborbital = "TODO"
libpng = "TODO"
libstdcxx = "TODO"
libvorbis = "TODO"
libxml2 = "TODO"
lua54 = "TODO"
nano = "TODO"
nasm = "TODO"
ncurses = "TODO"
netdb = "TODO"
netsurf = "TODO"
netutils = "TODO"
nghttp2 = "TODO"
openssl1 = "TODO"
orbclient = "TODO"
orbdata = "TODO"
orbital = "TODO"
orbterm = "TODO"
orbutils = "TODO"
patch = "TODO"
patchelf = "TODO"
pcre = "TODO"
pkgutils = "TODO"
pop-icon-theme = "TODO"
redoxfs = "TODO"
relibc = "TODO"
resist = "TODO"
ripgrep = "TODO"
sed = "TODO"
shared-mime-info = "TODO"
terminfo = "TODO"
userutils = "TODO"
uutils = "TODO"
vim = "TODO"
xz = "TODO"
zlib = "TODO"
