[packages]
base-initfs = "TODO"
base = "TODO"
bash = "TODO"
bootloader = "TODO"
ca-certificates = "TODO"
contain = "TODO"
coreutils = "TODO"
cosmic-edit = "TODO"
cosmic-files = "TODO"
cosmic-icons = "TODO"
cosmic-term = "TODO"
curl = "TODO"
dejavu = "TODO"
diffutils = "TODO"
drivers-initfs = "TODO"
drivers = "TODO"
expat = "TODO"
extrautils = "TODO"
findutils = "TODO"
freedoom = "TODO"
freetype2 = "TODO"
gdbserver = "TODO"
gettext = "TODO"
git = "TODO"
gnu-binutils = "TODO"
gnu-grep = "3.1"
gnu-make = "TODO"
hicolor-icon-theme = "TODO"
installer-gui = "TODO"
installer = "TODO"
ion = "TODO"
kernel = "TODO"
kibi = "TODO"
libgcc = "TODO"
libiconv = "TODO"
libjpeg = "TODO"
liborbital = "TODO"
libpng = "TODO"
libstdcxx = "TODO"
nano = "TODO"
nasm = "TODO"
netdb = "TODO"
netsurf = "TODO"
netutils = "TODO"
nghttp2 = "TODO"
openssl1 = "TODO"
orbclient = "TODO"
orbdata = "TODO"
orbital = "TODO"
orbutils = "TODO"
patch = "2.7.6"
patchelf = "TODO"
pcre = "TODO"
pkgar = "TODO"
pkgutils = "TODO"
pop-icon-theme = "TODO"
prboom = "TODO"
redoxerd = "TODO"
redoxfs = "TODO"
relibc = "TODO"
resist = "TODO"
ripgrep = "TODO"
sed = "TODO"
shared-mime-info = "TODO"
strace = "TODO"
terminfo = "TODO"
userutils = "TODO"
uutils = "TODO"
vim = "TODO"
xz = "TODO"
zlib = "TODO"
