name: Run setup.sh

on:
  workflow_dispatch:

jobs:
  run-setup:
    runs-on: ubuntu-latest

    container:
      image: willnode/redox-os-builder:latest
      volumes:
       - /mnt:/mnt

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run setup.sh
        run: |
          echo "verbose = off" > $HOME/.wgetrc
          cp -a $GITHUB_WORKSPACE /mnt/repo
          cd /mnt/repo
          bash ./setup.sh
          df -h
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /mnt/repo/redox/cookbook/repo
          publish_branch: gh-pages
