name: Run setup-partial.sh

on:
  workflow_dispatch:
    inputs:
      recipes:
        description: 'Recipe names (space separated)'
        required: true

jobs:
  run-setup-partial:
    runs-on: ubuntu-latest

    container:
      image: willnode/redox-os-builder:pkg
      volumes:
       - /mnt:/mnt

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      SSH_SCP_PATH: ${{ vars.SSH_SCP_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Setup and Test SCP
        run: |
          mkdir -p $HOME/.ssh; (echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa); chmod 0600 $HOME/.ssh/id_rsa;
          export SSH_CMD="scp -r -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
          TARGET=/mnt/repo/pkg; mkdir -p $TARGET; echo "hello" > $TARGET/.test
          $SSH_CMD $TARGET/.test $SSH_SCP_PATH/pkg/
          export $EX_REPO=$GITHUB_WORKSPACE/artifacts/$ARCH-unknown-redox; mkdir -p $EX_REPO
          $SSH_CMD $SSH_SCP_PATH/pkg/$ARCH-unknown-redox/repo.toml $EX_REPO/ || true

      - name: Run setup.sh
        run: |
          echo "verbose = off" > $HOME/.wgetrc
          export ARTIFACTS=$GITHUB_WORKSPACE/artifacts
          rm -rf /mnt/repo; cp -a $GITHUB_WORKSPACE/repo /mnt/repo
          cd /mnt/repo; bash ./setup-partial.sh "${{ github.event.inputs.recipes }}"
          df -h

      - name: Push via SCP
        run: |
          export SSH_CMD="scp -r -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
          $SSH_CMD /mnt/repo/redox/cookbook/repo/* $SSH_SCP_PATH/pkg/
