name: Run setup-toolchain.sh

on:
  workflow_dispatch:

jobs:
  run-setup-partial:
    runs-on: ubuntu-24.04-arm

    container:
      image: willnode/redox-os-builder:latest
      volumes:
        - /mnt:/mnt

    env:
      SSH_SCP_PATH: ${{ vars.SSH_SCP_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Setup and Test SCP
        run: |
          mkdir -p $HOME/.ssh; (echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa); chmod 0600 $HOME/.ssh/id_rsa;
          export SSH_CMD="scp -r -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
          TARGET=/mnt/repo/toolchain; mkdir -p $TARGET; echo "hello" > $TARGET/.test
          $SSH_CMD $TARGET/.test $SSH_SCP_PATH/toolchain/

      - name: Run setup-toolchain.sh
        run: |
          echo "verbose = off" > $HOME/.wgetrc
          rm -rf /mnt/repo; cp -a $GITHUB_WORKSPACE/repo /mnt/repo
          cd /mnt/repo; bash ./setup-toolchain.sh
          df -h

      - name: Push via SCP
        run: |
          export SSH_CMD="scp -r -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
          $SSH_CMD /mnt/repo/toolchain/* $SSH_SCP_PATH/toolchain/
