name: Run setup.sh using custom Docker container

on:
  workflow_dispatch:

jobs:
  run-setup:
    runs-on: ubuntu-latest

    container:
      image: willnode/redox-os-builder:latest
      options: --privileged  # Remove if not needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run setup.sh
        run: bash ./setup.sh
