name: Check space

on:
  workflow_dispatch:

jobs:
  run-setup:
    runs-on: ubuntu-latest

    container:
      image: willnode/redox-os-builder:latest
      options: --privileged  # Remove if not needed
      volumes:
       - /mnt:/mnt
    steps:
      - name: Run DF
        run: |
          df -h
          cat /mnt/DATALOSS_WARNING_README.txt
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: '/mnt/repo'
      - name: Run DF Again
        run: |
          df -h
          cd /mnt/repo
          ls -lh
