name: Check space

on:
  workflow_dispatch:

jobs:
  run-setup:
    runs-on: ubuntu-latest

    container:
      image: willnode/redox-os-builder:latest
      options: --privileged  # Remove if not needed
      volumes:
       - /mnt:/mnt
    steps:
      - name: Run DF
        run: |
          df -h
          cat /mnt/DATALOSS_WARNING_README.txt
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run DF Again
        run: |
          df -h
          cp -a $GITHUB_WORKSPACE /mnt/repo
          cd /mnt/repo
          ls -lh
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /mnt/repo/build
          publish_branch: gh-pages
