name: Check space

on:
  workflow_dispatch:

jobs:
  run-setup:
    runs-on: ubuntu-latest
    container:
      image: willnode/redox-os-builder:latest
      options: --cap-add SYS_ADMIN --device /dev/fuse
      volumes:
       - /mnt:/mnt
    steps:
      - name: Check fuse
        run: |
          df -h
          cat /mnt/DATALOSS_WARNING_README.txt
          ls /dev
          ls /dev/fuse
